package main

import (
	"fmt"
	"text/template"
)

var fileTemplate = template.Must(template.New("models").Parse(
	`// Generated by github.com/emicklei/dgraph-access/cmd/dggen. DO NOT EDIT
package {{ .PackageName }}
import ({{ range .Imports }}
	{{.}}{{ end }}		
)
{{ range .Types }}
type {{.Name}} struct {
	dga.Node ` + "`json:\",inline\"`" + ` {{ range .Fields }}
        {{ .Name }} {{ .TypeDefinition }} {{ .Annotation }} {{ end }}
}
{{ end }}
`))

type FileData struct {
	PackageName string
	Imports     []string
	Types       []TypeData
}

type TypeData struct {
	Name   string
	Fields []FieldData
}

type FieldData struct {
	Name           string
	TypeDefinition string
	Annotation     string
}

func (f *FileData) EnsureImport(i string) {
	for _, each := range f.Imports {
		if each == i {
			return // already listed
		}
	}
	f.Imports = append(f.Imports, fmt.Sprintf("%q", i))
}
